import numpy as np
import matplotlib.pyplot as plt
from matplotlib.collections import LineCollection


def _make_grid(xy_lim: float, vis_n: int):
    """Return (X, Y, pts) meshgrid + flattened query points."""
    g    = np.linspace(-xy_lim, xy_lim, vis_n)
    X, Y = np.meshgrid(g, g)
    pts  = np.stack([X.ravel(), Y.ravel()], axis=1)
    return X, Y, pts


def _density_grid(gmm, xy_lim: float, vis_n: int):
    """
    Evaluate gmm.density on a (vis_n, vis_n) square grid.
    Returns the density map [X, Y, Z(density)]
    """
    X, Y, pts = _make_grid(xy_lim, vis_n)
    Z = gmm.density(pts).reshape(vis_n, vis_n)
    return X, Y, Z


def _density_bg(ax, X, Y, Z, color: str, n_lev: int, alpha_max: float = 1.0):
    """
    fill density contour (transparent outside, opaque inside).

    Args:
        ax (matplotlib.axes.Axes): The axes object to draw on.
        X (np.ndarray): X coordinates of the 2D grid (usually generated by np.meshgrid).
        Y (np.ndarray): Y coordinates of the 2D grid.
        Z (np.ndarray): Density or probability values corresponding to the (X, Y) grid points.
        color (str): Name or Hex code of the fill color (e.g., 'red', '#ff0000').
        n_lev (int): Number of contour levels to divide into. More levels mean a smoother gradient.
        alpha_max (float, optional): Maximum opacity at the center (highest density).
                                     Range [0, 1], defaults to 1.0 (fully opaque).
    """
    z_ceil  = Z.max() * 1.001
    levels  = np.linspace(Z.max() * 0.05, Z.max(), n_lev)
    alphas  = np.linspace(0.04, alpha_max, n_lev)
    for i in range(len(levels) - 1):
        ax.contourf(X, Y, Z, levels=[levels[i], levels[i + 1]],
                    colors=[color], alpha=alphas[i])
    ax.contourf(X, Y, Z, levels=[levels[-1], z_ceil],
                colors=[color], alpha=alphas[-1])


def plot_trajectories(ax, traj: list, gmm,
                      xy_lim: float = 6.0,
                      vis_n: int = 200,
                      n_traj: int = 100,
                      traj_steps: int = 40,
                      density_color: str = 'steelblue',
                      beta_min: float = None,
                      beta_max: float = None,
                      T: float = None,
                      pt_color: str = 'firebrick') -> LineCollection:
    """
    Plot particle trajectories during the reverse diffusion (t = T -> 0).

    Trajectories are coloured by progress through the plasma colormap:
        purple  ->  t = T  (pure noise)
        yellow  ->  t ~= 0  (generated data)

    Args:
        ax            : matplotlib Axes to draw on.
        traj          : list of (N, D) arrays returned by a solver
                        (index 0 = t=T, index -1 = t~=0).
        gmm           : gaussian_mix object -- used for the background density.
        xy_lim        : axis half-width.
        vis_n         : grid resolution for the background density (vis_n x vis_n).
        n_traj        : number of particles whose paths are rendered.
        traj_steps    : subsample the trajectory to this many time snapshots.
        density_color : fill colour for the p_0 background contours.
        beta_min      : VP-SDE schedule parameter -- required to draw p_T overlay.
        beta_max      : VP-SDE schedule parameter -- required to draw p_T overlay.
        T             : diffusion end time -- required to draw p_T overlay.
        pt_color      : fill colour for the p_T overlay contours.

    Returns:
        lc : the LineCollection (pass to fig.colorbar to add a time colorbar).
    """
    X, Y, pts = _make_grid(xy_lim, vis_n)

    # p_0 background (faint) -- shows where particles should end up
    Z0 = gmm.density(pts).reshape(vis_n, vis_n)
    _density_bg(ax, X, Y, Z0, color=density_color, n_lev=10, alpha_max=0.25)

    # p_T overlay (faint) -- shows where particles start from
    if beta_min is not None and beta_max is not None and T is not None:
        ZT = gmm.vp_density(pts, T, beta_min, beta_max).reshape(vis_n, vis_n)
        _density_bg(ax, X, Y, ZT, color=pt_color, n_lev=10, alpha_max=0.25)

    # subsample time steps
    n_particles = min(n_traj, traj[0].shape[0])
    idx  = np.round(np.linspace(0, len(traj) - 1, traj_steps)).astype(int)
    sub  = np.array([traj[i][:n_particles] for i in idx])  # (traj_steps, n_particles, D)

    # build segments for LineCollection: one segment per consecutive pair per particle
    segs_all, time_all = [], []
    for k in range(n_particles):
        pts_k = sub[:, k, :]                                   # (traj_steps, D)
        segs  = np.stack([pts_k[:-1], pts_k[1:]], axis=1)     # (traj_steps-1, 2, D)
        segs_all.append(segs)
        time_all.append(np.linspace(0.0, 1.0, traj_steps - 1))

    segs_all = np.concatenate(segs_all)   # (n_particles*(traj_steps-1), 2, D)
    time_all = np.concatenate(time_all)   # same length

    lc = LineCollection(segs_all, cmap='plasma',
                        norm=plt.Normalize(0, 1),
                        linewidth=0.5, alpha=0.5)
    lc.set_array(time_all)
    ax.add_collection(lc)

    # mark start (noise) and end (data)
    ax.scatter(sub[0, :, 0],  sub[0, :, 1],
               s=8,  color='#9944ff', alpha=0.8, zorder=5, label=r'$x_T$')
    ax.scatter(sub[-1, :, 0], sub[-1, :, 1],
               s=10, color='#ffe033', alpha=0.9, zorder=6, label=r'$x_0$')

    ax.set_xlim(-xy_lim, xy_lim)
    ax.set_ylim(-xy_lim, xy_lim)
    ax.set_aspect('equal')
    ax.legend(fontsize=7, loc='upper right', markerscale=1.5)
    return lc


def plot_samples(ax, samples: np.ndarray, gmm,
                 xy_lim: float = 6.0,
                 vis_n: int = 200,
                 n_levels: int = 15,
                 density_color: str = 'steelblue',
                 t: float = None,
                 beta_min: float = None,
                 beta_max: float = None) -> None:
    """
    Plot generated samples overlaid on a density background.

    By default the background shows p_0 (the original GMM).  If t, beta_min,
    and beta_max are all provided, the background shows p_t instead -- useful
    for visualising intermediate diffusion states.

    Args:
        ax            : matplotlib Axes to draw on.
        samples       : (N, D) array of generated samples (e.g. traj[-1]).
        gmm           : gaussian_mix object -- used for the background density.
        xy_lim        : axis half-width.
        vis_n         : grid resolution for the background density (vis_n x vis_n).
        n_levels      : number of contourf bands in the density background.
        density_color : fill colour for the background density contours.
        t             : diffusion time for p_t background; None -> use p_0.
        beta_min      : VP-SDE schedule parameter (required when t is not None).
        beta_max      : VP-SDE schedule parameter (required when t is not None).
    """
    X, Y, pts = _make_grid(xy_lim, vis_n)

    if t is not None and beta_min is not None and beta_max is not None:
        Z = gmm.vp_density(pts, t, beta_min, beta_max).reshape(vis_n, vis_n)
    else:
        Z = gmm.density(pts).reshape(vis_n, vis_n)

    _density_bg(ax, X, Y, Z, color=density_color, n_lev=n_levels, alpha_max=1.0)

    ax.scatter(samples[:, 0], samples[:, 1],
               s=4, alpha=0.4, color='white', linewidths=0)
    ax.set_xlim(-xy_lim, xy_lim)
    ax.set_ylim(-xy_lim, xy_lim)
    ax.set_aspect('equal')
